<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Users [
        <!ELEMENT Users (User)+>
        <!ELEMENT User (Surname, Name, Login, Password, Account)>
        <!ELEMENT Surname (#PCDATA)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Account (Balance)>
        <!ELEMENT Balance (#PCDATA)>
        ]>
<Users>

    <User>

        <Surname>
            Ivanov
        </Surname>

        <Name>
            Ivan
        </Name>

        <Login>
            Ivan
        </Login>

        <Password>
            Ivan1
        </Password>

        <Account>

            <Balance>
                1000
            </Balance>


        </Account>


    </User>

    <User>

        <Surname>
            Petrov
        </Surname>

        <Name>
            Petya
        </Name>

        <Login>
            Petya
        </Login>

        <Password>
            Petya1
        </Password>

        <Account>

            <Balance>
                2000
            </Balance>


        </Account>


    </User>


</Users>