=== Khmelov/JD2016-08-22/src/by/it/snegurskiy/jd02_08/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://snegurskiy.it-academy.by/jd02_07/xml_class"
    xmlns:tns="http://snegurskiy.it-academy.by/jd02_07/xml_class"
    elementFormDefault="qualified">

    <element name="Users">
        <complexType>
            <sequence>
                <element name="User" type="tns:User" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

    <complexType name="User">
        <sequence>
            <element name="Surname" type="string"></element>
            <element name="Name" type="string"></element>
            <element name="Login" type="string"></element>
            <element name="Password" type="string"></element>
            <element name="Account" type="tns:Account"></element>

        </sequence>
    </complexType>

    <complexType name="Account">
        <all>
            <element name="Balance" type="double"></element>

        </all>
    </complexType>

</schema>

=== Khmelov/JD2016-08-22/src/by/it/snegurskiy/jd02_08/user+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns="http://snegurskiy.it-academy.by/jd02_07/xml_class"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://snegurskiy.it-academy.by/jd02_07/xml_class user.xsd">

        <User>
            <Surname>
                Ivanov
            </Surname>
            <Name>
                Ivan
            </Name>
            <Login>
                Ivan
            </Login>
            <Password>
                Ivan1
            </Password>
            <Account>

                    <Balance>
                        1000
                    </Balance>


            </Account>


        </User>

    <User>
        <Surname>
            Petrov
        </Surname>
        <Name>
            Petya
        </Name>
        <Login>
            Petya
        </Login>
        <Password>
            Petya1
        </Password>
        <Account>

            <Balance>
                2000
            </Balance>


        </Account>


    </User>


    </Users>
